version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    image: app:pokedex_django
    container_name: pokedex_django_container
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 &&
        python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=django-insecure-*+w55m7@hiq%afpvb_^x=s@6%!yh64x54hdv_b#viti-(678y#
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    container_name: pokedex_django_postgres_db
