# Generated by Django 3.2.12 on 2022-02-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokedexCreature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ref_number', models.PositiveSmallIntegerField()),
                ('type_1', models.CharField(max_length=20)),
                ('type_2', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.PositiveSmallIntegerField()),
                ('hp', models.PositiveSmallIntegerField()),
                ('attack', models.PositiveSmallIntegerField()),
                ('defense', models.PositiveSmallIntegerField()),
                ('special_attack', models.PositiveSmallIntegerField()),
                ('special_defence', models.PositiveSmallIntegerField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('generation', models.PositiveSmallIntegerField()),
                ('legendary', models.BooleanField(default=False)),
            ],
        ),
    ]
