# Generated by Django 3.2.12 on 2022-02-12 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('pokedex_creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pokedexcreature')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
