# Generated by Django 3.2.12 on 2022-02-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pokemon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokedexcreature',
            options={'ordering': ['name']},
        ),
    ]
